version: "3"

services:
  database:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./docker/database/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
